name: 'Invalidate Cloudfront'
description: 'Invalidate Cloudfront distribution paths'
author: 'Pixelcop Research, Inc.'
branding:
  icon: 'cloud-lightning'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
