name: "Test Suite"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run tests on"
        required: false
        default: "test"

jobs:
  tests:
    name: "Test ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: "${{ inputs.branch }}"

      - name: print versions
        shell: bash
        run: |
          uname
          uname -a
          aws --version
          jq --version
          jq --help

      - name: invalidate PATHS
        uses: ./
        env:
          DEBUG: "1"
          PATHS: /robots* /index.html
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: create path files
        shell: bash
        run: |
          cat << EOF > paths1.txt
          /robots.txt
          /*.xml
          EOF

          cat << EOF > paths2.txt
          /robots.txt /*.xml
          EOF

      - name: invalidate PATHS_FROM 1
        uses: ./
        env:
          DEBUG: "1"
          PATHS_FROM: paths1.txt
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: invalidate PATHS_FROM 2
        uses: ./
        env:
          DEBUG: "1"
          PATHS_FROM: paths2.txt
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
